Map lugatKey = {
  'make': 'bajarmoq, majburlamoq',
  'gate': 'darvoza',
  'mane': 'yol',
  'street': 'ko’cha',
  'he': 'u(mujskoyrod)',
  'steel': 'po’lat, temir',
  'these': 'bular',
  'nine': 'to’qqiz',
  'tie': 'galstuk, bog’lamoq',
  'my': 'mening',
  'fly':'pasha, uchmoq',
  'pipe':'truba(quvur)',
  'rice':'guruch',
  'type':'pechatqilmoq, tur',
  'kite':'varrak',
  // 'white':'oq',
  // 'nose':'burun',
  // 'no':'yo’q, emas',
  // 'pole':'qutb, ustun',
  // 'home':'uy',
  // 'tulip':'lola',
  // 'six':'olti',
  // 'it':'u(sredniy rod)',
  // 'still':'hanuz, sokin',
  // 'pick':'termoq, tanlamoq',
  // 'pen':'ruchka',
  // 'left':'chap',
  // 'dress':'ko’ylak, kiy(intir)moq',
  // 'net':'to’r, sof',
  // 'set':'to’plam, o’rnatmoq',
  // 'text':'matn',
  // 'bag':'sumka',
  // 'man':'erkakkishi',
  // 'lamp':'lampa, chiroq',
  // 'hat':'shapka, shylapa',
  // 'that':'anau',
  // 'fat':'yog’, semiz',
  // 'rat':'kalamush',
  // 'tram':'tramvay',
  // 'fox':'tulki',
  // 'sock':'paypoq',
  // 'kind':'mehribon, muloyim, tur',
  // 'whatkindof':'qanday',
  // 'good':'yaxshi',
  // 'too':'o’ta, juda, ham',
  // 'room':'hona, joy',
  // 'spoon':'qoshiq',
  // 'food':'ovqat',
  // 'soon':'tezorada',
  // 'colour':'rang, rangbermoq',
  // 'park':'bog’, parkovka qilmoq',
  // 'yard':'xovli',
  // 'scarf':'sharf',
  // 'harm':'zarar, zarar yetkazmoq',
  // 'farm':'ferma',
  // 'fork':'vilka',
  // 'or':'yoki',
  // 'norm':'meyor',
  // 'girl':'qizbola',
  // 'first':'birinchi',
  // 'skirt':'yubka',
  // 'her':'uni, uning…',
  // 'turn':'burilish, burilmoq, navbat',
  // 'bird':'qush',
  // 'fur':'mo’yna',
  // 'term':'atama, semester, shart',
  // 'Exercise -book':'daftar',
  // 'bench':'skameyka',
  // 'chair':'stul, rais, raislik qilmoq',
  // 'shirt':'ko’ylak',
  // 'chess':'shaxmat',
  // 'chest':'ko’krak qafasi, sandiq',
  // 'ship':'kema',
  // 'open':'ochiq, ochmoq',
  // 'sofa':'divan',
  // 'letter':'xat, xarf',
  // 'dinner':'tushlik',
  // 'lesson':'dars',
  // 'farmer':'fermer',
  // 'over':'ustidan',
  // 'pepper':'murch',
  // 'former':'sobiq',
  // 'count':'sanamoq',
  // 'blouse':'kofta',
  // 'town':'shaxarcha',
  // 'brown':'jigarrang',
  // 'sound':'ovoz, tovush eshitilmoq',
  // 'power':'kuch, tok',
  // 'point':'nuqta, ishora qilmoq',
  // 'noise':'shovqin, ovoz',
  // 'window':'deraza',
  // 'yellow':'sariq',
  // 'shallow':'sayoz',
  // 'hold':'Ushlab turmoq, o’tkazmoq',
  // 'worker':'ishchi',
  // 'how':'qanday',
  // 'put':'qo’ymoq, joylashtirmoq',
  // 'read':'o’qimoq',
  // 'sea':'dengiz',
  // 'leaf':'barg',
  // 'lead':'Yetaklamoq olib bormoq',
  // 'leave':'tarketmoq',
  // 'which':'qaysi',
  // 'well':'quduq, yaxshi',
  // 'grow':'o’s(tir)moq',
  // 'slow':'sekin',
  // 'blow':'esmoq, puflamoq',
  // 'ball':'koptok',
  // 'small':'kichik',
  // 'call':'telqilmoq, chaqirmoq',
  // 'fall':'yiqilmoq, kuz',
  // 'stall':'peshtaxta',
  // 'war':'urush',
  // 'warn':'ogohlantirmoq',
  // 'warm':'iliq, isitmmoq',
  // 'sweet':'shirin',
  // 'eight':'sakkiz',
  // 'they':'ular',
  // 'grey':'kulrang',
  // 'play':'o’yin, o’ynamoq, pyessa',
  // 'say':'aytmoq',
  // 'right':'o’ng, to’g’ri, xaq-xuquq',
  // 'day':'kun',
  // 'four':'to’rt',
  // 'fair':'malla, yarmarka, adolatli',
  // 'field':'dala, soxa',
  // 'factory':'fabrika',
  // 'eleven':'o’n bir',
  // 'thirteen':'o’n uch',
  // 'sixteen':'o’n olti',
  // 'thirty':'o’ttiz',
  // 'fifty':'ellik',
  // 'ninety':'to’qson',
  // 'hundred':'yuz',
  // 'suit':'kostyum, moskelmoq',
  // 'glass':'stakan, shisha',
  // 'sideboard':'servant',
  // 'here':'shuyer',
  // 'there':'uyer',
  // 'square':'kvadrat, maydon',
  // 'very':'juda',
  // 'key':'kalit',
  // 'king':'qirol',
  // 'kingdom':'qirollik',
  // 'lane':'torko’cha, yo’lak',
  // 'basket':'savat',
  // 'some':'ba’zi, biroz, birnecha',
  // 'heart':'yurak',
  // 'draw':'chizmoq, sudramoq, tortmoq',
  // 'come':'kelmoq',
  // 'you':'sen, siz',
  // 'your':'sening, sizning',
  // 'his':'uning',
  // 'their':'ularmig',
  // 'its':'uning',
  // 'happy':'quvnoq, xursand',
  // 'till':'gacha',
  // 'monday':'dushanba',
  // 'thursday':'payshanba',
  // 'february':'febral',
  // 'march':'mart',
  // 'april':'aprel',
  // 'june':'iyun',
  // 'july':'iyul',
  // 'november':'noyabr',
  // 'have':'Ega bo’lmoq',
  // 'daughter':'qiz',
  // 'brother':'aka, uka',
  // 'mother':'ona',
  // 'parents':'Ota-ona',
  // 'aunt':'amma, hola',
  // 'village':'qishloq',
  // 'stocking':'chulki',
  // 'morning':'tong',
  // 'thank':'Rahmat aytmoq, minnatdor bo’lmoq',
  // 'think':'o’ylamoq',
  // 'wink':'ko’zqismoq',
  // 'wing':'qanot',
  // 'bring':'olibkelmoq',
  // 'sing':'kuylamoq',
  // 'ring':'uzuk, jiringlamoq',
  // 'spring':'prujina, buloq, sakrash, sakramoq, baxor',
  // 'Living-room':'mexmonxona',
  // 'Dining-room':'oshxona',
  // 'above':'ustida',
  // 'infrontof':'oldida',
  // 'inthemiddleof':'o’rtasida',
  // 'behind':'orqasida',
  // 'between':'orasida',
  // 'wrong':'xato, noto’g’ri',
  // 'Put smth on':'Kiyib olmoq',
  // 'Take smth off':'Yechmoq (kiyimni)',
  // 'Kitchen-garden':'tomorqa',
  // 'poor':'bechora, kambag’al',
  // 'address':'manzil, murojaat qilmoq',
  // 'Number':'raqam, son',
  // 'Moon':'oy',
  // 'Last':'o’tgan, davom etmoq',
  // 'Each':'xar',
  // 'Alone':'yolg’iz',
  // 'Rest':'dam, dam olmoq',
  // 'Except':'Dan tashqari',
  // 'Leap':'sakrash, sakramoq',
  // 'Leap-year':'Kabisa yili',
  // 'Way':'yo’l, usul, yo’sin',
  // 'Often':'Tez-tez',
  // 'Sometimes':'ba’zan',
  // 'Always':'doimo',
  // 'Every':'xar',
  // 'Piece':'bo’lak, parcha, qism',
  // 'Peace':'tinchlik',
  // 'Part':'bo’lak, qism',
  // 'Quarter':'chorak',
  // 'Board':'tahta',
  // 'Drink':'ichimlik, ichmoq',
  // 'Touch':'tegmoq',
  // 'Far':'uzoq',
  // 'Once':'Bir marotaba, qachonki',
  // 'Atonce':'darrov',
  // 'Just':'adolatli, endiroqda, faqat',
  // 'Everything':'Hamma narsa',
  // 'Learn':'o’rganmoq, o’qimoq',
  // 'Age':'asr, yosh',
  // 'Leather':'charm',
  // 'Use':'foyda, foydalanmoq',
  // 'Because':'chunki',
  // 'Same':'birxil, aynan',
  // 'Loud':'baland(ovoz)',
  // 'Itdoesnotmatter':'Ahamiyati yo’q',
  // 'Duty':'burch, vazifa, boj',
  // 'Present':'sovg’a, taqdim etmoq',
  // 'Tobepresent':'Mavjud bo’lmoq',
  // 'Hard':'qattiq, qiyin',
  // 'Tooth':'tish',
  // 'Push':'turtmoq',
  // 'Jump':'sakrash, sakramoq',
  // 'Love':'sevgi, sevmoq',
  // 'Before':'avval, oldin, ilgari',
  // 'For':'uchun, mobaynida, chunki',
  // 'Large':'katta',
  // 'But':'ammo, lekin, biroq, …dan tashqari',
  // 'Fine':'ajoyib, zo’r, jarima, jarima solmoq',
  // 'Bookcase':'kitobjavoni',
  // 'Case':'sumka, kelishik, ish(yuridik)',
  // 'Doll':'qo’g’irchoq',
  // 'Pleasure':'xuzur, xalovat',
  // 'Question':'savol, so’roqqilmoq',
  // 'Tobemadeof':'yasalgan',
  // 'Correct':'to’g’ri, to’g’rilamoq',
  // 'Mug':'krujka',
  // 'Unit':'birlik',
  // 'Jacket':'jiket, kostyum',
  // 'Raincoat':'plash',
  // 'Describe':'tasvirlamoq',
  // 'Dormitory':'yotoqxona',
  // 'Out':'...dan',
  // 'Either(or)':'yo',
  // 'Neither(nor)':'na',
  //     'Carry':'ko’tarib yurmoq, tashimoq',
  // 'Let':'Ruxsat bermoq',
  // 'Introduce':'tanishtirmoq',
  // 'Glad':'xursand',
  // 'Sentence':'gap, xukm, xukmqilmoq',
  // 'Afternoon':'Tushdan keyin',
  // 'Midday':'Kun o’rtasi, qiyomvaqti',
  // 'Midnight':'Yarim kecha',
  // 'Wear':'Kiyib yurmoq',
  // 'Tobecalled':'atalmoq',
  // 'Clothes':'kiyimlar',
  // 'Cotton':'paxta',
  // 'Wool':'yung',
  // 'Nylon':'neylon',
  // 'Thousand':'ming',
  // 'Tights':'kolgotki',
  // 'Situation':'xolat, vaziyat',
  // 'Description':'ta’rif, tasvir',
  // 'Find':'topmoq',
  // 'Mild':'yumshoq(xarakter, ob xavo)',
  // 'Might':'kuch, qudrat, mumkin',
  // 'Light':'yengil, yorug’, tutashtirmoq',
  // 'Talk':'suhbat, gaplashmoq',
  // 'Choose':'tanlamoq',
  // 'Course':'kurs, yo’nalish',
  // 'Don’t mentionit':'arzimaydi',
  // 'Difficult':'qiyin',
  // 'Ready':'tayyor',
  // 'To be ready for':'Biror narsau/ntayyorbo’lmoq',
  //     'Conversation':'suhbat',
  // 'Definite':'aniq',
  // 'Article':'maqola, artikl',
  // 'Compare':'taqqoslamoq',
  // 'Apple - tree':'Olma daraxti',
  // 'Institute':'institute',
  // 'University':'universitet',
  // 'Profession':'kasb',
  // 'Lookafter':'parvarishqilmoq',
  // 'Lookfor':'izlamoq',
  // 'Wish':'tilak, tilamoq',
  // 'Slogan':'shior',
  // 'Meeting':'uchrashuv',
  // 'Demonstration':'namoyish',
  // 'Impressive':'ta’sirli, taassurotqoldiruvchi',
  // 'Sharp':'o’tkir',
  // 'Claw':'tirnoq(xayvon)',
  // 'Runaway':'qochibketmoq',
  // 'Cinema':'kinoteatr',
  // 'Film':'plyonka, film',
  // 'Hospital':'kasalxona',
  // 'Know':'bilmoq',
  // 'Machine':'uskuna',
  // 'Milk maid':'Sut sog’uvchi',
  // 'Playground':'o’yinmaydoni',
  // 'Sorry':'afsuslanmoq',
  // 'Tractor':'traktor',
  // 'Care':'g’amxo’rlik, ~qilmoq',
  // 'Stairs':'zina',
  // 'Pair':'(bir)juft',
  // 'Hear':'eshitmoq',
  // 'Clear':'aniq, ravshan',
  // 'Cheer':'Dalda bermoq',
  // 'Fear':'qo’rquv, qo’rqmoq',
  // 'Quick':'tez',
  // 'Quite':'sokin, tinch',
  // 'Few':'Bir necha',
  // 'Other':'boshqa',
  // 'Another':'boshqa',
  // 'Hang':'ilmoq, osmoq',
  // 'Alotof':'ko’p',
  // 'Centre':'markaz',
  // 'Balcony':'balkon',
  // 'Shed':'ombor',
  // 'Duck':'o’rdak',
  // 'Forest':'o’rmon',
};
