List values= [
'bajarmoq, majburlamoq',
'darvoza',
'yol',
'ko’cha',
'u(mujskoyrod)',
'po’lat, temir',
'bular',
'to’qqiz',
'galstuk, bog’lamoq',
'mening',
'pasha, uchmoq',
'truba(quvur)',
'guruch',
'pechatqilmoq, tur',
'varrak',
'oq',
'burun',
'yo’q, emas',
'qutb, ustun',
'uy',
'lola',
'olti',
'u(sredniy rod)',
'hanuz, sokin',
'termoq, tanlamoq',
'ruchka',
'chap',
'ko’ylak, kiy(intir)moq',
'to’r, sof',
'to’plam, o’rnatmoq',
'matn',
'sumka',
'erkakkishi',
'lampa, chiroq',
'shapka, shylapa',
'anau',
'yog’, semiz',
'kalamush',
'tramvay',
'tulki',
'paypoq',
'mehribon, muloyim, tur',
'qanday',
'yaxshi',
'o’ta, juda, ham',
'hona, joy',
'qoshiq',
'ovqat',
'tezorada',
'rang, rangbermoq',
'bog’, parkovka qilmoq',
'xovli',
'sharf',
'zarar, zarar yetkazmoq',
'ferma',
'vilka',
'yoki',
'meyor',
'qizbola',
'birinchi',
'yubka',
'uni, uning…',
'burilish, burilmoq, navbat',
'qush',
'mo’yna',
'atama, semester, shart',
'daftar',
'skameyka',
'stul, rais, raislik qilmoq',
'ko’ylak',
'shaxmat',
'ko’krak qafasi, sandiq',
'kema',
'ochiq, ochmoq',
'divan',
'xat, xarf',
'tushlik',
'dars',
'fermer',
'ustidan',
'murch',
'sobiq',
'sanamoq',
'kofta',
'shaxarcha',
'jigarrang',
'ovoz, tovush eshitilmoq',
'kuch, tok',
'nuqta, ishora qilmoq',
'shovqin, ovoz',
'deraza',
'sariq',
'sayoz',
'Ushlab turmoq, o’tkazmoq',
'ishchi',
'qanday',
'qo’ymoq, joylashtirmoq',
'o’qimoq',
'dengiz',
'barg',
'Yetaklamoq olib bormoq',
'tarketmoq',
'qaysi',
'quduq, yaxshi',
'o’s(tir)moq',
'sekin',
'esmoq, puflamoq',
'koptok',
'kichik',
'telqilmoq, chaqirmoq',
'yiqilmoq, kuz',
'peshtaxta',
'urush',
'ogohlantirmoq',
'iliq, isitmmoq',
'shirin',
'sakkiz',
'ular',
'kulrang',
'o’yin, o’ynamoq, pyessa',
'aytmoq',
'o’ng, to’g’ri, xaq-xuquq',
'kun',
'to’rt',
'malla, yarmarka, adolatli',
'dala, soxa',
'fabrika',
'o’n bir',
'o’n uch',
'o’n olti',
'o’ttiz',
'ellik',
'to’qson',
'yuz',
'kostyum, moskelmoq',
'stakan, shisha',
'servant',
'shuyer',
'uyer',
'kvadrat, maydon',
'juda',
'kalit',
'qirol',
'qirollik',
'torko’cha, yo’lak',
'savat',
'ba’zi, biroz, birnecha',
'yurak',
'chizmoq, sudramoq, tortmoq',
'kelmoq',
'sen, siz',
'sening, sizning',
'uning',
'ularmig',
'uning',
'quvnoq, xursand',
'gacha',
'dushanba',
'payshanba',
'febral',
'mart',
'aprel',
'iyun',
'iyul',
'noyabr'
'Ega bo’lmoq'
'qiz'
'aka, uka'
'ona'
'Ota-ona'
'amma, hola'
'qishloq'
'chulki'
'tong'
'Rahmat aytmoq, minnatdor bo’lmoq'
'o’ylamoq'
'ko’zqismoq'
'qanot'
'olibkelmoq'
'kuylamoq'
'uzuk, jiringlamoq'
'prujina, buloq, sakrash, sakramoq, baxor',
'mexmonxona'
'oshxona'
'ustida'
'oldida'
'o’rtasida'
'orqasida'
'orasida'
'xato, noto’g’ri'
'Kiyib olmoq'
'Yechmoq (kiyimni)'
'tomorqa'
'bechora, kambag’al'
'manzil, murojaat qilmoq'
'raqam, son'
'oy'
'o’tgan, davom etmoq'
'xar'
'yolg’iz',
'dam, dam olmoq',
'Dan tashqari',
'sakrash, sakramoq',
'Kabisa yili',
'yo’l, usul, yo’sin',
'Tez-tez',
'ba’zan',
'doimo',
'xar',
'bo’lak, parcha, qism',
'tinchlik',
'bo’lak, qism',
'chorak',
'tahta',
'ichimlik, ichmoq',
'tegmoq',
'uzoq',
'Bir marotaba, qachonki',
'darrov',
'adolatli, endiroqda, faqat',
'Hamma narsa',
'o’rganmoq, o’qimoq',
'asr, yosh',
'charm',
'foyda, foydalanmoq',
'chunki',
'birxil, aynan',
'baland(ovoz)',
'Ahamiyati yo’q',
'burch, vazifa, boj',
'sovg’a, taqdim etmoq',
'Mavjud bo’lmoq',
'qattiq, qiyin',
'tish',
'turtmoq',
'sakrash, sakramoq',
'sevgi, sevmoq',
'avval, oldin, ilgari',
'uchun, mobaynida, chunki',
'katta',
'ammo, lekin, biroq, …dan tashqari',
'ajoyib, zo’r, jarima, jarima solmoq',
'kitobjavoni',
'sumka, kelishik, ish(yuridik)',
'qo’g’irchoq',
'xuzur, xalovat',
'savol, so’roqqilmoq',
'yasalgan',
'to’g’ri, to’g’rilamoq',
'krujka',
'birlik',
'jiket, kostyum',
'plash',
'tasvirlamoq',
'yotoqxona',
'...dan',
'yo',
'na',
'ko’tarib yurmoq, tashimoq',
'Ruxsat bermoq',
'tanishtirmoq',
'xursand',
'gap, xukm, xukmqilmoq',
'Tushdan keyin',
'Kun o’rtasi, qiyomvaqti',
'Yarim kecha',
'Kiyib yurmoq',
'atalmoq',
'kiyimlar',
'paxta',
'yung',
'neylon',
'ming',
'kolgotki',
'xolat, vaziyat',
'ta’rif, tasvir',
'topmoq',
'yumshoq(xarakter, ob xavo)',
'kuch, qudrat, mumkin',
'yengil, yorug’, tutashtirmoq',
'suhbat, gaplashmoq',
'tanlamoq',
'kurs, yo’nalish',
'arzimaydi',
'qiyin',
'tayyor',
'Biror narsau/ntayyorbo’lmoq',
'suhbat',
'aniq',
'maqola, artikl',
'taqqoslamoq',
'Olma daraxti',
'institute',
'universitet',
'kasb',
'parvarishqilmoq',
'izlamoq',
'tilak, tilamoq',
'shior',
'uchrashuv',
'namoyish',
'ta’sirli, taassurotqoldiruvchi',
'o’tkir',
'tirnoq(xayvon)',
'qochibketmoq',
'kinoteatr',
'plyonka, film',
'kasalxona',
'bilmoq',
'uskuna',
'Sut sog’uvchi',
'o’yinmaydoni',
'afsuslanmoq',
'traktor',
'g’amxo’rlik, ~qilmoq',
'zina',
'(bir)juft',
'eshitmoq',
'aniq, ravshan',
'Dalda bermoq',
'qo’rquv, qo’rqmoq',
'tez',
'sokin, tinch',
'Bir necha',
'boshqa',
'boshqa',
'ilmoq, osmoq',
'ko’p',
'markaz',
'balkon',
'ombor',
'o’rdak',
'o’rmon',

];